### ISSUE TITLE
Adding Formatter (Toolbar feature)

### ISSUE THREAD

**Issue by prakhar2611** [prakhar2611/lexical-app#12]
Add feature to select text and turn it into styled `block` like heading or list

**Comment by anubhavtomargaya** [comment]
npm install @lexical/selection if not installed already.

Selection Interface
https://lexical.dev/docs/api/modules/lexical_selection
 
Available Nodes and Classes in Lexical
https://lexical.dev/docs/api/modules/lexical

About nodes
https://lexical.dev/docs/concepts/nodes

Create plugin that formats or creates a type of node.
GetSelection and check if its of type RangeSelection
CreateNode with passing selection to the node. This should format or create new styled node in editor.

Pass the plugin into Editor init config
Add this node to nodes in init

**Comment by anubhavtomargaya** [comment]
added a formatter and creator both at toolbar using createHeadingNode  and setBlocksType.
