### ISSUE TITLE
Adding Basic Nodes (Toolbar features)

### ISSUE THREAD

**Issue by prakhar2611** [prakhar2611/lexical-app#8]

**Comment by anubhavtomargaya** [comment]
added a button (where the toolbar will be) to turn selection into Big heading
- imported HeadingNode(added to nodes in initialConfig, $createHeadingNote from '@lexical/rich-text';
- built a plugin HeadingToolbarPlugin
- used getSelection and createHeadingnode 
- also need to add createTextNode for default text to appear [todo]
